import { ReactQueryProvider } from "@/components/react-query-provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <AntdRegistry>{children} </AntdRegistry>
      </ReactQueryProvider>
    </html>
  );
}
