import { queryClient } from "@/lib/react-query";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ minHeight: "100vh", display: "flex", flex: "1 1 0%" }}>
        <AntdRegistry>{children} </AntdRegistry>
      </body>
    </html>
  );
}
