import { ReactQueryProvider } from "@/components/react-query-provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body>
          <AntdRegistry>
            <ReactQueryProvider>
              {children}

              <ReactQueryDevtools initialIsOpen={false} />
            </ReactQueryProvider>
          </AntdRegistry>
        </body>
      </html>
    </ClerkProvider>
  );
}
